// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY1G6BIozX7WVE2hncjcEjDp-h4N5Smws',
    appId: '1:902980273680:ios:665fc4bed3b03c7870ec95',
    messagingSenderId: '902980273680',
    projectId: 'test-a9672',
    storageBucket: 'test-a9672.firebasestorage.app',
    iosBundleId: 'com.example.cornaro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnx9Z7PGzjr1Vfu72t5Drz6nvukRIafXk',
    appId: '1:902980273680:web:41f7b82cfa66a29570ec95',
    messagingSenderId: '902980273680',
    projectId: 'test-a9672',
    authDomain: 'test-a9672.firebaseapp.com',
    storageBucket: 'test-a9672.firebasestorage.app',
    measurementId: 'G-V7XE5E8E14',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnx9Z7PGzjr1Vfu72t5Drz6nvukRIafXk',
    appId: '1:902980273680:web:08d49cbaf8d9d34a70ec95',
    messagingSenderId: '902980273680',
    projectId: 'test-a9672',
    authDomain: 'test-a9672.firebaseapp.com',
    storageBucket: 'test-a9672.firebasestorage.app',
    measurementId: 'G-Y2VW0KP94H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY1G6BIozX7WVE2hncjcEjDp-h4N5Smws',
    appId: '1:902980273680:ios:665fc4bed3b03c7870ec95',
    messagingSenderId: '902980273680',
    projectId: 'test-a9672',
    storageBucket: 'test-a9672.firebasestorage.app',
    iosBundleId: 'com.example.cornaro',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCukFMDV6kW96Mzvo3WVyzjp5yWPe2gEsg',
    appId: '1:902980273680:android:eda4f17f61c5fe9970ec95',
    messagingSenderId: '902980273680',
    projectId: 'test-a9672',
    storageBucket: 'test-a9672.firebasestorage.app',
  );

}